# Site settings
title: Flake8 Rules
email: grantmcconnaughey@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Descriptions and examples for each of the rules in Flake8 (pyflakes, pycodestyle, and mccabe).
  Pulled directly from <a href="https://lintly.com">Lintly</a>, the continuous
  Python code linting application.
baseurl: "/Flake8Rules" # the subpath of your site, e.g. /blog
url: "https://lintlyci.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gmcconnaughey
github_username:  grantmcconnaughey

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
collections:
  rules:
    output: true
  rules_json:
    output: true
    permalink: /api/rules/:title/
defaults:
  - scope:
      path: "_rules_json"
    values:
      layout: rule_json
  - scope:
      path: "_rules"
    values:
      layout: rule


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
